### ISSUE TITLE
Creation tool fails to parse GRIB files with lambert_lam projection

### ISSUE THREAD

**Issue by tnipen** [ecmwf/anemoi-datasets#157]
**Describe the bug**
Dataset building fails for GRIB files with "lambert_lam" projection. earthkit.data fails to detect the name of the projection and therefore cannot determine the resolution, which anemoi.dataset expects.

**Version number**
I am using the following versions/branch/sha1 of the anemoi packages:
anemoi-datasets==0.5.12
anemoi-transform==0.1.0
anemoi-utils==0.4.9
earthkit-data==0.11.4
earthkit-geo==0.3.0
earthkit-meteo==0.3.0

**To Reproduce**
1. pip install anemoi-datasets[create]
2. Save the test YAML file:
```
dates:
  start: 2024-12-03T06:00:00Z
  end: 2024-12-03T06:00:00Z
  frequency: 1h

input:
  join:
    - grib:
        path: "GRIBPFDEOD+0006h00m00s"
        levtype: sfc
        param: [2t]
```
3. Copy the sample data available on ATOS: /lus/h2resw01/scratch/fatn/DE330/GRIBPFDEOD+0006h00m00s
4. Run `anemoi-datasets create test.yaml test.zarr`
5. Here is the error log:
```
2024-12-10 22:09:51 INFO 🎬 Task init((),{}) starting
2024-12-10 22:09:51 INFO Setting flatten_grid=True in config
2024-12-10 22:09:51 INFO Setting ensemble_dimension=2 in config
2024-12-10 22:09:51 INFO Setting flatten_grid=True in config
2024-12-10 22:09:51 INFO Setting ensemble_dimension=2 in config
2024-12-10 22:09:51 INFO {'start': datetime.datetime(2024, 12, 3, 6, 0, tzinfo=datetime.timezone.utc), 'end': datetime.datetime(2024, 12, 3, 6, 0, tzinfo=datetime.timezone.utc), 'frequency': '1h', 'group_by': 'monthly'}
2024-12-10 22:09:51 INFO Groups(dates=1,<anemoi.datasets.dates.StartEndDates object at 0x7272ddba76d0>)
2024-12-10 22:09:51 INFO JoinAction: 
  FunctionAction: path=GRIBPFDEOD+0006h00m00s levtype=sfc param=['2t'] 
2024-12-10 22:09:51 INFO Groups: Groups(dates=1,<anemoi.datasets.dates.StartEndDates object at 0x7272ddba76d0>)
2024-12-10 22:09:51 INFO Minimal input for 'init' step (using only the first date) : GroupOfDates(dates=['2024-12-03T06:00:00'])
2024-12-10 22:09:51 INFO JoinResult: 1 dates (2024-12-03:06)
  grib(GroupOfDates(dates=['2024-12-03T06:00:00']))
2024-12-10 22:09:51 INFO Config loaded ok:
2024-12-10 22:09:51 INFO Found 1 datetimes.
2024-12-10 22:09:51 INFO Dates: Found 1 datetimes, in 1 groups: 
2024-12-10 22:09:51 INFO Missing dates: 0
Traceback (most recent call last):
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/utils/cli.py", line 153, in cli_main
    cmd.run(args)
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/commands/create.py", line 72, in run
    self.serial_create(args)
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/commands/create.py", line 82, in serial_create
    task("init", options)
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/commands/create.py", line 36, in task
    result = c.run()
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/create/__init__.py", line 392, in run
    return self._run()
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/create/__init__.py", line 414, in _run
    variables = self.minimal_input.variables
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/create/input/result.py", line 538, in variables
    self.build_coords()
  File "/home/thomasn/deps/lib/python3.10/site-packages/anemoi/datasets/create/input/result.py", line 527, in build_coords
    self._resolution = first_field.resolution
  File "/home/thomasn/deps/lib/python3.10/site-packages/earthkit/data/core/fieldlist.py", line 378, in resolution
    return self._metadata.geography.resolution()
  File "/home/thomasn/deps/lib/python3.10/site-packages/earthkit/data/readers/grib/metadata.py", line 179, in resolution
    raise ValueError(f"Unknown gridType={grid_type}")
ValueError: Unknown gridType=lambert_lam
2024-12-10 22:09:51 ERROR 
💣 Unknown gridType=lambert_lam
2024-12-10 22:09:51 ERROR 💣 Exiting
```

**URL to sample input data**
The grib file is available on ATOS:

/lus/h2resw01/scratch/fatn/DE330/GRIBPFDEOD+0006h00m00s

**Expected behavior**
I expected the dataset to be created

**Comment by tnipen** [comment]
Another follow up comment. `earthkit.data` also fails to recognize the resolution for datasets on regular lat/lon (grid_type=regular_ll) grids that have different grid spacing in the latitude and longitude direction. This is used by the Austrian ReAnalysis, which is a regional reanalysis with DxInDegrees=0.028° and DyInDegrees=0.018°.

**Comment by caglarkucuk** [comment]
Adding on the previous comment from @tnipen on 'regular_ll' crs files for reproducibility:

**URL to sample input data**
This [OneDrive link](https://zamgacat-my.sharepoint.com/:f:/g/personal/ckuecuek_zamgacat_onmicrosoft_com/ErZN6BTOYNVCuIQ2xRt3vMgBWFx6t0NhY01_kmWHreKHrw?e=tj3Eo7)

**Sample yaml file**
```
dates:
  start: 2017-01-01T00:00:00Z
  end: 2017-01-01T01:00:00Z

input:
  join:
    - grib:
        path: /example_files/*.grb
        levtype: pl
        param:
        - u 
        level:
        - 1000
    - grib:
        path: /example_files/*.grb
        levtype: sfc
        param:
        - sp

statistics:
    allow_nans: [u]
```

Triggers assertion error in `earthkit.data.readers.grib` since DxInDegrees=0.028° and DyInDegrees=0.018°.

**Comment by floriankrb** [comment]
@tnipen The lambert azimutal projection should be handled correctly now by earthkit data. But I cannot test with your test file, which is not accessible to me. Could you confirm that the issue is fixed with earthkit.data >= 0.12.1, please ?

**Comment by tnipen** [comment]
@floriankrb I can confirm that both the problem (lambert_lam and regular_ll) are solved with the updated version of earthkit.data. Thanks so much for our help!
