### ISSUE TITLE
Error when combining datasets with different frequencies and unalligned start- and/or end-dates

### ISSUE THREAD

**Issue by mpvginde** [ecmwf/anemoi-datasets#91]
**Describe the bug**
Using `adjust: "all"` when opening two datasets with:
- differing frequencies and 
- where the start- and/or end-date of the dataset with highest frequency does not _line up_ with the dates of the dataset with the lowest frequency  

results in an `ValueError: Incompatible lengths:` error

**Version number**
0.5.8.dev14+geb63372

**To Reproduce**
on EMCWFs: `ATOS`
Run
```python
from anemoi.datasets import open_dataset

dataset = {"cutout":
            [
                {
                   #dataset starting at 1984-09-01 03:00:00 with frequency 3h
                    "dataset" : "/scratch/cu0k/ai-ml/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-1995-v1.zarr",
                    #"thinning" : 4
                },
                {
                    "dataset" : "/home/mlx/ai-ml/datasets/stable/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr"
                }
            ],
        "adjust" : "all"
        }

ds = open_dataset(dataset)
```
See error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/__init__.py", line 29, in open_dataset
    ds = _open_dataset(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/misc.py", line 267, in _open_dataset
    sets.append(_open(a))
                ^^^^^^^^
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/misc.py", line 186, in _open
    return _open_dataset(**a).mutate()
           ^^^^^^^^^^^^^^^^^^
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/misc.py", line 327, in _open_dataset
    return cutout_factory(args, kwargs).mutate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/grids.py", line 246, in cutout_factory
    return Cutout(
           ^^^^^^^
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/grids.py", line 134, in __init__
    super().__init__(datasets, axis)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/grids.py", line 96, in __init__
    super().__init__(datasets, axis)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/forwards.py", line 211, in __init__
    super().__init__(datasets)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/forwards.py", line 120, in __init__
    self.check_compatibility(self.datasets[0], d)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/forwards.py", line 219, in check_compatibility
    super().check_compatibility(d1, d2)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/forwards.py", line 177, in check_compatibility
    self.check_same_lengths(d1, d2)
  File "/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages/anemoi/datasets/data/forwards.py", line 160, in check_same_lengths
    raise ValueError(f"Incompatible lengths: {d1._len} and {d2._len}")
ValueError: Incompatible lengths: 16556 and 16555
```

**Comment by b8raoult** [comment]
Pull request was accepted and merged
